//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgentPonyWarcraftClient.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArgentPonyWarcraftClient.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:403, &quot;type&quot;:&quot;Forbidden&quot;, &quot;detail&quot;:&quot;Account Inactive&quot;}.
        /// </summary>
        internal static string AccountInactive403ForbiddenResponse {
            get {
                return ResourceManager.GetString("AccountInactive403ForbiddenResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement-category/?namespace=static-8.2.5_31884-us&quot;
        ///    }
        ///  },
        ///  &quot;categories&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement-category/81?namespace=static-8.2.5_31884-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Feats of Strength&quot;,
        ///      &quot;id&quot;: 81
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement-category/92?namespace=static-8.2.5_31884-us&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AchievementCategoriesIndexResponse {
            get {
                return ResourceManager.GetString("AchievementCategoriesIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement-category/81?namespace=static-8.2.5_31884-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 81,
        ///  &quot;name&quot;: &quot;Feats of Strength&quot;,
        ///  &quot;achievements&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement/456?namespace=static-8.2.5_31884-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Realm First! Obsidian Slayer&quot;,
        ///      &quot;id&quot;: 456
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AchievementCategoryResponse {
            get {
                return ResourceManager.GetString("AchievementCategoryResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/achievement/6?namespace=static-8.2.5_31884-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;icon&quot;,
        ///      &quot;value&quot;: &quot;https://render-us.worldofwarcraft.com/icons/56/achievement_level_10.jpg&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string AchievementMediaResponse {
            get {
                return ResourceManager.GetString("AchievementMediaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;id&quot;:2144,&quot;title&quot;:&quot;What a Long, Strange Trip It&apos;s Been&quot;,&quot;points&quot;:50,&quot;description&quot;:&quot;Complete the world events achievements listed below.&quot;,&quot;reward&quot;:&quot;Rewards: Violet Proto-Drake&quot;,&quot;rewardItems&quot;:[{&quot;id&quot;:44177,&quot;name&quot;:&quot;Reins of the Violet Proto-Drake&quot;,&quot;icon&quot;:&quot;ability_mount_drake_proto&quot;,&quot;quality&quot;:4,&quot;itemLevel&quot;:70,&quot;tooltipParams&quot;:{&quot;timewalkerLevel&quot;:0,&quot;azeritePower0&quot;:0,&quot;azeritePower1&quot;:0,&quot;azeritePower2&quot;:0,&quot;azeritePower3&quot;:0,&quot;azeritePowerLevel&quot;:0},&quot;stats&quot;:[],&quot;armor&quot;:0,&quot;context&quot;:&quot;&quot;,&quot;bonusLists&quot;:[],&quot;displayInfoId&quot;:0,&quot;arti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AchievementResponse {
            get {
                return ResourceManager.GetString("AchievementResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement/?namespace=static-8.2.5_31884-us&quot;
        ///    }
        ///  },
        ///  &quot;achievements&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement/6?namespace=static-8.2.5_31884-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Level 10&quot;,
        ///      &quot;id&quot;: 6
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement/7?namespace=static-8.2.5_31884-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Level 20&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AchievementsIndexResponse {
            get {
                return ResourceManager.GetString("AchievementsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/1146/auctions?namespace=dynamic-us&quot;
        ///    }
        ///  },
        ///  &quot;connected_realm&quot;: {
        ///    &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/1146?namespace=dynamic-us&quot;
        ///  },
        ///  &quot;auctions&quot;: [
        ///    {
        ///      &quot;id&quot;: 568957532,
        ///      &quot;item&quot;: {
        ///        &quot;id&quot;: 168185
        ///      },
        ///      &quot;quantity&quot;: 7,
        ///      &quot;unit_price&quot;: 345000,
        ///      &quot;time_left&quot;: &quot;SHORT&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 568957534,
        ///      &quot;item&quot;: {
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuctionsResponse {
            get {
                return ResourceManager.GetString("AuctionsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;challenge&quot;:[{&quot;realm&quot;:{&quot;name&quot;:&quot;Kargath&quot;,&quot;slug&quot;:&quot;kargath&quot;,&quot;battlegroup&quot;:&quot;Vindication&quot;,&quot;locale&quot;:&quot;en_US&quot;,&quot;timezone&quot;:&quot;America/New_York&quot;,&quot;connected_realms&quot;:[&quot;kargath&quot;,&quot;norgannon&quot;]},&quot;map&quot;:{&quot;id&quot;:1182,&quot;name&quot;:&quot;Auchindoun&quot;,&quot;slug&quot;:&quot;auchindoun&quot;,&quot;hasChallengeMode&quot;:true,&quot;bronzeCriteria&quot;:{&quot;time&quot;:3300000,&quot;hours&quot;:0,&quot;minutes&quot;:55,&quot;seconds&quot;:0,&quot;milliseconds&quot;:0,&quot;isPositive&quot;:true},&quot;silverCriteria&quot;:{&quot;time&quot;:1920000,&quot;hours&quot;:0,&quot;minutes&quot;:32,&quot;seconds&quot;:0,&quot;milliseconds&quot;:0,&quot;isPositive&quot;:true},&quot;goldCriteria&quot;:{&quot;time&quot;:1140000,&quot;hours&quot;:0,&quot;minu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChallengesResponse {
            get {
                return ResourceManager.GetString("ChallengesResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;achievements&quot;:[{&quot;id&quot;:92,&quot;achievements&quot;:[{&quot;id&quot;:6,&quot;title&quot;:&quot;Level 10&quot;,&quot;points&quot;:10,&quot;description&quot;:&quot;Reach level 10.&quot;,&quot;rewardItems&quot;:[],&quot;icon&quot;:&quot;achievement_level_10&quot;,&quot;criteria&quot;:[{&quot;id&quot;:5212,&quot;description&quot;:&quot;Reach level 10&quot;,&quot;orderIndex&quot;:1,&quot;max&quot;:10}],&quot;accountWide&quot;:false,&quot;factionId&quot;:2},{&quot;id&quot;:12547,&quot;title&quot;:&quot;Epic&quot;,&quot;points&quot;:10,&quot;description&quot;:&quot;Equip an item of at least Epic quality, with a minimum item level of 340, in every slot.&quot;,&quot;rewardItems&quot;:[],&quot;icon&quot;:&quot;inv_enchant_voidcrystal&quot;,&quot;criteria&quot;:[{&quot;id&quot;:40394,&quot;description&quot;:&quot;Head [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterAchievementsResponse {
            get {
                return ResourceManager.GetString("CharacterAchievementsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;classes&quot;:[{&quot;id&quot;:1,&quot;mask&quot;:1,&quot;powerType&quot;:&quot;rage&quot;,&quot;name&quot;:&quot;Warrior&quot;},{&quot;id&quot;:12,&quot;mask&quot;:2048,&quot;powerType&quot;:&quot;fury&quot;,&quot;name&quot;:&quot;Demon Hunter&quot;}]}.
        /// </summary>
        internal static string CharacterClassesResponse {
            get {
                return ResourceManager.GetString("CharacterClassesResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;races&quot;:[{&quot;id&quot;:1,&quot;mask&quot;:1,&quot;side&quot;:&quot;alliance&quot;,&quot;name&quot;:&quot;Human&quot;},{&quot;id&quot;:30,&quot;mask&quot;:536870912,&quot;side&quot;:&quot;alliance&quot;,&quot;name&quot;:&quot;Lightforged Draenei&quot;}]}.
        /// </summary>
        internal static string CharacterRacesResponse {
            get {
                return ResourceManager.GetString("CharacterRacesResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;lastModified&quot;:1534891127000,&quot;name&quot;:&quot;Thorpe&quot;,&quot;realm&quot;:&quot;Norgannon&quot;,&quot;battlegroup&quot;:&quot;Vindication&quot;,&quot;class&quot;:1,&quot;race&quot;:1,&quot;gender&quot;:0,&quot;level&quot;:115,&quot;achievementPoints&quot;:15685,&quot;thumbnail&quot;:&quot;norgannon/168/107804072-avatar.jpg&quot;,&quot;calcClass&quot;:&quot;Z&quot;,&quot;faction&quot;:0,&quot;guild&quot;:{&quot;name&quot;:&quot;Mythical Warriors&quot;,&quot;realm&quot;:&quot;Norgannon&quot;,&quot;battlegroup&quot;:&quot;Vindication&quot;,&quot;members&quot;:159,&quot;achievementPoints&quot;:1610,&quot;emblem&quot;:{&quot;icon&quot;:12,&quot;iconColor&quot;:&quot;ff092a5d&quot;,&quot;iconColorId&quot;:10,&quot;border&quot;:0,&quot;borderColor&quot;:&quot;ff00317c&quot;,&quot;borderColorId&quot;:10,&quot;backgroundColor&quot;:&quot;ffffffff&quot;,&quot;backg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterResponse {
            get {
                return ResourceManager.GetString("CharacterResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;characters&quot;:[{&quot;name&quot;:&quot;Erlian&quot;,&quot;realm&quot;:&quot;Cenarius&quot;,&quot;battlegroup&quot;:&quot;Cyclone&quot;,&quot;class&quot;:2,&quot;race&quot;:1,&quot;gender&quot;:0,&quot;level&quot;:8,&quot;achievementPoints&quot;:0,&quot;thumbnail&quot;:&quot;cenarius/235/108809963-avatar.jpg&quot;,&quot;lastModified&quot;:0},{&quot;name&quot;:&quot;Drinian&quot;,&quot;realm&quot;:&quot;Norgannon&quot;,&quot;battlegroup&quot;:&quot;Vindication&quot;,&quot;class&quot;:1,&quot;race&quot;:1,&quot;gender&quot;:0,&quot;level&quot;:110,&quot;achievementPoints&quot;:19290,&quot;thumbnail&quot;:&quot;norgannon/249/107811065-avatar.jpg&quot;,&quot;spec&quot;:{&quot;name&quot;:&quot;Fury&quot;,&quot;role&quot;:&quot;DPS&quot;,&quot;backgroundImage&quot;:&quot;bg-warrior-fury&quot;,&quot;icon&quot;:&quot;ability_warrior_innerrage&quot;,&quot;description&quot;:&quot;A fur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharactersResponse {
            get {
                return ResourceManager.GetString("CharactersResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement/6?namespace=static-8.2.5_31884-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 6,
        ///  &quot;category&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement-category/92?namespace=static-8.2.5_31884-us&quot;
        ///    },
        ///    &quot;name&quot;: &quot;Character&quot;,
        ///    &quot;id&quot;: 92
        ///  },
        ///  &quot;name&quot;: &quot;Level 10&quot;,
        ///  &quot;description&quot;: &quot;Reach level 10.&quot;,
        ///  &quot;points&quot;: 10,
        ///  &quot;is_account_wide&quot;: false,
        ///  &quot;criteria&quot;: {
        ///    &quot;id&quot;: 2050,
        ///    &quot;description&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameDataAchievementResponse {
            get {
                return ResourceManager.GetString("GameDataAchievementResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;achievements&quot;:[{&quot;id&quot;:15089,&quot;achievements&quot;:[{&quot;id&quot;:5130,&quot;title&quot;:&quot;Diplomacy&quot;,&quot;points&quot;:10,&quot;description&quot;:&quot;Raise 15 reputations to Exalted.&quot;,&quot;rewardItems&quot;:[],&quot;icon&quot;:&quot;achievement_reputation_02&quot;,&quot;criteria&quot;:[{&quot;id&quot;:17453,&quot;description&quot;:&quot;The League of Arathor&quot;,&quot;orderIndex&quot;:0,&quot;max&quot;:42000},{&quot;id&quot;:19732,&quot;description&quot;:&quot;The Anglers&quot;,&quot;orderIndex&quot;:70,&quot;max&quot;:42000}],&quot;accountWide&quot;:false,&quot;factionId&quot;:0},{&quot;id&quot;:5812,&quot;title&quot;:&quot;United Nations&quot;,&quot;points&quot;:15,&quot;description&quot;:&quot;Raise 55 reputations to Exalted.&quot;,&quot;reward&quot;:&quot;Reward: Dark Phoenix  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GuildAchievementsResponse {
            get {
                return ResourceManager.GetString("GuildAchievementsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;lastModified&quot;:1528412536000,&quot;name&quot;:&quot;Mythical Warriors&quot;,&quot;realm&quot;:&quot;Norgannon&quot;,&quot;battlegroup&quot;:&quot;Vindication&quot;,&quot;level&quot;:25,&quot;side&quot;:0,&quot;achievementPoints&quot;:1610,&quot;emblem&quot;:{&quot;icon&quot;:12,&quot;iconColor&quot;:&quot;ff092a5d&quot;,&quot;iconColorId&quot;:10,&quot;border&quot;:0,&quot;borderColor&quot;:&quot;ff00317c&quot;,&quot;borderColorId&quot;:10,&quot;backgroundColor&quot;:&quot;ffffffff&quot;,&quot;backgroundColorId&quot;:49}}.
        /// </summary>
        internal static string GuildResponse {
            get {
                return ResourceManager.GetString("GuildResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;item_classes&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Consumable&quot;,
        ///      &quot;id&quot;: 0
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/1?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Container&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemClassesIndexResponse {
            get {
                return ResourceManager.GetString("ItemClassesIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;classes&quot;:[{&quot;class&quot;:17,&quot;name&quot;:&quot;Battle Pets&quot;,&quot;subclasses&quot;:[{&quot;subclass&quot;:0,&quot;name&quot;:&quot;BattlePet&quot;}]},{&quot;class&quot;:2,&quot;name&quot;:&quot;Weapon&quot;,&quot;subclasses&quot;:[{&quot;subclass&quot;:1378,&quot;name&quot;:&quot;Two-Handed Melee Weapon&quot;},{&quot;subclass&quot;:20,&quot;name&quot;:&quot;Fishing Pole&quot;}]}]}.
        /// </summary>
        internal static string ItemClassesResponse {
            get {
                return ResourceManager.GetString("ItemClassesResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;class_id&quot;: 0,
        ///  &quot;name&quot;: &quot;Consumable&quot;,
        ///  &quot;item_subclasses&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0/item-subclass/0?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Explosives and Devices&quot;,
        ///      &quot;id&quot;: 0
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-clas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemClassResponse {
            get {
                return ResourceManager.GetString("ItemClassResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item/19019?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 19019,
        ///  &quot;name&quot;: &quot;Thunderfury, Blessed Blade of the Windseeker&quot;,
        ///  &quot;quality&quot;: {
        ///    &quot;type&quot;: &quot;LEGENDARY&quot;,
        ///    &quot;name&quot;: &quot;Legendary&quot;
        ///  },
        ///  &quot;level&quot;: 58,
        ///  &quot;required_level&quot;: 60,
        ///  &quot;media&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/item/19019?namespace=static-8.3.0_32861-us&quot;
        ///    },
        ///    &quot;id&quot;: 19019
        ///  },
        ///  &quot;item_class&quot;: {        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemGameDataResponse {
            get {
                return ResourceManager.GetString("ItemGameDataResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/item/19019?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;icon&quot;,
        ///      &quot;value&quot;: &quot;https://render-us.worldofwarcraft.com/icons/56/inv_sword_39.jpg&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 19019
        ///}.
        /// </summary>
        internal static string ItemMediaResponse {
            get {
                return ResourceManager.GetString("ItemMediaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;id&quot;:18803,&quot;disenchantingSkillRank&quot;:0,&quot;description&quot;:&quot;Property of Finkle Einhorn, Grandmaster Adventurer&quot;,&quot;name&quot;:&quot;Finkle&apos;s Lava Dredger&quot;,&quot;icon&quot;:&quot;inv_gizmo_02&quot;,&quot;stackable&quot;:1,&quot;itemBind&quot;:1,&quot;bonusStats&quot;:[{&quot;stat&quot;:40,&quot;amount&quot;:13},{&quot;stat&quot;:5,&quot;amount&quot;:98},{&quot;stat&quot;:7,&quot;amount&quot;:23}],&quot;itemSpells&quot;:[],&quot;buyPrice&quot;:457008,&quot;itemClass&quot;:2,&quot;itemSubClass&quot;:5,&quot;containerSlots&quot;:0,&quot;weaponInfo&quot;:{&quot;damage&quot;:{&quot;min&quot;:43,&quot;max&quot;:56,&quot;exactMin&quot;:43.0,&quot;exactMax&quot;:56.0},&quot;weaponSpeed&quot;:3.6,&quot;dps&quot;:13.75},&quot;inventoryType&quot;:17,&quot;equippable&quot;:true,&quot;itemLevel&quot;:70 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemResponse {
            get {
                return ResourceManager.GetString("ItemResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;id&quot;:1060,&quot;name&quot;:&quot;Deep Earth Vestments&quot;,&quot;setBonuses&quot;:[{&quot;description&quot;:&quot;Reduces the mana cost of Healing Touch and Rejuvenation by 5%.&quot;,&quot;threshold&quot;:2},{&quot;description&quot;:&quot;Your Rejuvenation and Regrowth spells have a 10% chance to Timeslip and have double the normal duration.&quot;,&quot;threshold&quot;:4}],&quot;items&quot;:[76749,76750,76751,76752,76753]}.
        /// </summary>
        internal static string ItemSetResponse {
            get {
                return ResourceManager.GetString("ItemSetResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0/item-subclass/0?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;class_id&quot;: 0,
        ///  &quot;subclass_id&quot;: 0,
        ///  &quot;display_name&quot;: &quot;Explosives and Devices&quot;,
        ///  &quot;hide_subclass_in_tooltips&quot;: true
        ///}.
        /// </summary>
        internal static string ItemSubclassResponse {
            get {
                return ResourceManager.GetString("ItemSubclassResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-encounter/89?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 89,
        ///  &quot;name&quot;: &quot;Glubtok&quot;,
        ///  &quot;description&quot;: &quot;In a fit of rage, Glubtok unleashed his potent magical abilities and reduced his ogre mound to ash. Upon hearing of his destructive talents, the Defias hired the massive ogre mage to supervise their laborers as head foreman of the Deadmines.&quot;,
        ///  &quot;creatures&quot;: [
        ///    {
        ///      &quot;id&quot;: 358,
        ///      &quot;name&quot;: &quot;Glu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalEncounterResponse {
            get {
                return ResourceManager.GetString("JournalEncounterResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-encounter/89?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 89,
        ///  &quot;name&quot;: &quot;Glubtok&quot;,
        ///  &quot;description&quot;: &quot;In a fit of rage, Glubtok unlea.
        /// </summary>
        internal static string JournalEncounterResponseTruncated {
            get {
                return ResourceManager.GetString("JournalEncounterResponseTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-encounter/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;encounters&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-encounter/89?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Glubtok&quot;,
        ///      &quot;id&quot;: 89
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-encounter/90?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalEncountersIndexResponse {
            get {
                return ResourceManager.GetString("JournalEncountersIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-expansion/68?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 68,
        ///  &quot;name&quot;: &quot;Classic&quot;,
        ///  &quot;dungeons&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-instance/227?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Blackfathom Deeps&quot;,
        ///      &quot;id&quot;: 227
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-instance/228?namesp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalExpansionResponse {
            get {
                return ResourceManager.GetString("JournalExpansionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-expansion/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;tiers&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-expansion/68?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Classic&quot;,
        ///      &quot;id&quot;: 68
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-expansion/70?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalExpansionsIndexResponse {
            get {
                return ResourceManager.GetString("JournalExpansionsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/journal-instance/63?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;tile&quot;,
        ///      &quot;value&quot;: &quot;https://render-us.worldofwarcraft.com/zones/deadmines-small.jpg&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string JournalInstanceMediaResponse {
            get {
                return ResourceManager.GetString("JournalInstanceMediaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-instance/63?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 63,
        ///  &quot;name&quot;: &quot;Deadmines&quot;,
        ///  &quot;map&quot;: {
        ///    &quot;name&quot;: &quot;Deadmines&quot;,
        ///    &quot;id&quot;: 36
        ///  },
        ///  &quot;area&quot;: {
        ///    &quot;name&quot;: &quot;The Deadmines&quot;,
        ///    &quot;id&quot;: 1581
        ///  },
        ///  &quot;description&quot;: &quot;It is said the Deadmines&apos; gold deposits once accounted for a third of Stormwind&apos;s treasure reserves. Amid the chaos of the First War, the mines were abandoned and later thought to be [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalInstanceResponse {
            get {
                return ResourceManager.GetString("JournalInstanceResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-instance/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;instances&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-instance/63?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Deadmines&quot;,
        ///      &quot;id&quot;: 63
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-instance/64?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalInstancesIndexResponse {
            get {
                return ResourceManager.GetString("JournalInstancesIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;mounts&quot;:[{&quot;name&quot;:&quot;High Priest&apos;s Lightsworn Seeker&quot;,&quot;spellId&quot;:229377,&quot;creatureId&quot;:122124,&quot;itemId&quot;:0,&quot;qualityId&quot;:1,&quot;icon&quot;:&quot;inv_priestmount&quot;,&quot;isGround&quot;:true,&quot;isFlying&quot;:true,&quot;isAquatic&quot;:false,&quot;isJumping&quot;:false},{&quot;name&quot;:&quot;Ivory Hawkstrider&quot;,&quot;spellId&quot;:230401,&quot;creatureId&quot;:-73991,&quot;itemId&quot;:142369,&quot;qualityId&quot;:4,&quot;icon&quot;:&quot;inv_ability_mount_cockatricemount_white&quot;,&quot;isGround&quot;:true,&quot;isFlying&quot;:false,&quot;isAquatic&quot;:true,&quot;isJumping&quot;:true}]}.
        /// </summary>
        internal static string MountsResponse {
            get {
                return ResourceManager.GetString("MountsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pet/39?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 39,
        ///  &quot;name&quot;: &quot;Mechanical Squirrel&quot;,
        ///  &quot;battle_pet_type&quot;: {
        ///    &quot;id&quot;: 9,
        ///    &quot;type&quot;: &quot;MECHANICAL&quot;,
        ///    &quot;name&quot;: &quot;Mechanical&quot;
        ///  },
        ///  &quot;description&quot;: &quot;A mechanical squirrel&apos;s logic center tells it to collect and store both nuts and bolts for the winter.&quot;,
        ///  &quot;is_capturable&quot;: false,
        ///  &quot;is_tradable&quot;: true,
        ///  &quot;is_battlepet&quot;: true,
        ///  &quot;is_alliance_only&quot;: false,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PetResponse {
            get {
                return ResourceManager.GetString("PetResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pet/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;pets&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pet/39?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Mechanical Squirrel&quot;,
        ///      &quot;id&quot;: 39
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pet/40?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Bombay Cat&quot;,
        ///      &quot;id&quot;: 40        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PetsIndexResponse {
            get {
                return ResourceManager.GetString("PetsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;petTypes&quot;:[{&quot;id&quot;:0,&quot;key&quot;:&quot;humanoid&quot;,&quot;name&quot;:&quot;Humanoid&quot;,&quot;typeAbilityId&quot;:238,&quot;strongAgainstId&quot;:1,&quot;weakAgainstId&quot;:7},{&quot;id&quot;:1,&quot;key&quot;:&quot;dragonkin&quot;,&quot;name&quot;:&quot;Dragonkin&quot;,&quot;typeAbilityId&quot;:245,&quot;strongAgainstId&quot;:5,&quot;weakAgainstId&quot;:3}]}.
        /// </summary>
        internal static string PetTypesResponse {
            get {
                return ResourceManager.GetString("PetTypesResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;rows&quot;:[{&quot;ranking&quot;:1,&quot;rating&quot;:2775,&quot;name&quot;:&quot;Dno&quot;,&quot;realmId&quot;:1566,&quot;realmName&quot;:&quot;Area 52&quot;,&quot;realmSlug&quot;:&quot;area-52&quot;,&quot;raceId&quot;:6,&quot;classId&quot;:11,&quot;specId&quot;:105,&quot;factionId&quot;:1,&quot;genderId&quot;:1,&quot;seasonWins&quot;:288,&quot;seasonLosses&quot;:41,&quot;weeklyWins&quot;:0,&quot;weeklyLosses&quot;:0},{&quot;ranking&quot;:2,&quot;rating&quot;:2739,&quot;name&quot;:&quot;Bluegator&quot;,&quot;realmId&quot;:11,&quot;realmName&quot;:&quot;Tichondrius&quot;,&quot;realmSlug&quot;:&quot;tichondrius&quot;,&quot;raceId&quot;:2,&quot;classId&quot;:7,&quot;specId&quot;:264,&quot;factionId&quot;:1,&quot;genderId&quot;:0,&quot;seasonWins&quot;:433,&quot;seasonLosses&quot;:109,&quot;weeklyWins&quot;:0,&quot;weeklyLosses&quot;:0}]}.
        /// </summary>
        internal static string PvpLeaderboardResponse {
            get {
                return ResourceManager.GetString("PvpLeaderboardResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;id&quot;:13146,&quot;title&quot;:&quot;Generosity Abounds&quot;,&quot;reqLevel&quot;:77,&quot;suggestedPartyMembers&quot;:0,&quot;category&quot;:&quot;Icecrown&quot;,&quot;level&quot;:80}.
        /// </summary>
        internal static string QuestResponse {
            get {
                return ResourceManager.GetString("QuestResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;realms&quot;:[{&quot;type&quot;:&quot;pvp&quot;,&quot;population&quot;:&quot;n/a&quot;,&quot;queue&quot;:false,&quot;status&quot;:true,&quot;name&quot;:&quot;Aegwynn&quot;,&quot;slug&quot;:&quot;aegwynn&quot;,&quot;battlegroup&quot;:&quot;Vengeance&quot;,&quot;locale&quot;:&quot;en_US&quot;,&quot;timezone&quot;:&quot;America/Chicago&quot;,&quot;connected_realms&quot;:[&quot;daggerspine&quot;,&quot;bonechewer&quot;,&quot;gurubashi&quot;,&quot;hakkar&quot;,&quot;aegwynn&quot;]},{&quot;type&quot;:&quot;pve&quot;,&quot;population&quot;:&quot;low&quot;,&quot;queue&quot;:false,&quot;status&quot;:true,&quot;name&quot;:&quot;Aerie Peak&quot;,&quot;slug&quot;:&quot;aerie-peak&quot;,&quot;battlegroup&quot;:&quot;Vindication&quot;,&quot;locale&quot;:&quot;en_US&quot;,&quot;timezone&quot;:&quot;America/Los_Angeles&quot;,&quot;connected_realms&quot;:[&quot;aerie-peak&quot;]}]}.
        /// </summary>
        internal static string RealmsResponse {
            get {
                return ResourceManager.GetString("RealmsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;id&quot;:33994,&quot;name&quot;:&quot;Precise Strikes&quot;,&quot;profession&quot;:&quot;Enchanting&quot;,&quot;icon&quot;:&quot;spell_holy_greaterheal&quot;}.
        /// </summary>
        internal static string RecipeResponse {
            get {
                return ResourceManager.GetString("RecipeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;id&quot;:79733,&quot;name&quot;:&quot;Commanding Shout&quot;,&quot;icon&quot;:&quot;ability_warrior_rallyingcry&quot;,&quot;description&quot;:&quot;Increases maximum health of all party members within 20 yards by 20.  Lasts 2 min.&quot;,&quot;castTime&quot;:&quot;Instant&quot;,&quot;cooldown&quot;:&quot;30 sec cooldown&quot;}.
        /// </summary>
        internal static string SpellResponse {
            get {
                return ResourceManager.GetString("SpellResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;1&quot;:{&quot;specs&quot;:[{&quot;name&quot;:&quot;Arms&quot;,&quot;role&quot;:&quot;DPS&quot;,&quot;backgroundImage&quot;:&quot;bg-warrior-arms&quot;,&quot;icon&quot;:&quot;ability_warrior_savageblow&quot;,&quot;description&quot;:&quot;A battle-hardened master of two-handed weapons, using mobility and overpowering attacks to strike his opponents down.&quot;,&quot;order&quot;:0},{&quot;name&quot;:&quot;Fury&quot;,&quot;role&quot;:&quot;DPS&quot;,&quot;backgroundImage&quot;:&quot;bg-warrior-fury&quot;,&quot;icon&quot;:&quot;ability_warrior_innerrage&quot;,&quot;description&quot;:&quot;A furious berserker wielding a weapon in each hand, unleashing a flurry of attacks to carve her opponents to pieces.&quot;,&quot;order&quot;:1},{&quot;name&quot;:&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TalentsResponse {
            get {
                return ResourceManager.GetString("TalentsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;battletag&quot;:&quot;Drinian#1121&quot;,&quot;id&quot;:1742837}.
        /// </summary>
        internal static string UserResponse {
            get {
                return ResourceManager.GetString("UserResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;status&quot;:&quot;nok&quot;, &quot;reason&quot;: &quot;unable to get zone information.&quot;}.
        /// </summary>
        internal static string Zone404ErrorResponse {
            get {
                return ResourceManager.GetString("Zone404ErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;id&quot;:4131,&quot;name&quot;:&quot;Magister&apos;s Terrace&quot;,&quot;urlSlug&quot;:&quot;magisters-terrace&quot;,&quot;description&quot;:&quot;After his defeat in Tempest Keep, Kael&apos;thas Sunstrider publicly revealed his alliance with the ruthless Burning Legion. Intent upon summoning the demon lord Kil&apos;jaeden, Kael&apos;thas has returned to the Isle of Quel&apos;Danas to make the final preparations for his master&apos;s arrival.&quot;,&quot;location&quot;:{&quot;id&quot;:4080,&quot;name&quot;:&quot;Isle of Quel&apos;Danas&quot;},&quot;expansionId&quot;:1,&quot;numPlayers&quot;:&quot;5&quot;,&quot;isDungeon&quot;:true,&quot;isRaid&quot;:false,&quot;advisedMinLevel&quot;:68,&quot;advisedMaxLeve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZoneResponse {
            get {
                return ResourceManager.GetString("ZoneResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;zones&quot;:[{&quot;id&quot;:6912,&quot;name&quot;:&quot;Auchindoun&quot;,&quot;urlSlug&quot;:&quot;auchindoun&quot;,&quot;description&quot;:&quot;Auchindoun is the holy mausoleum of the draenei, a sanctum of the Light in which the spirits of the dead find respite. The crystalline structure also serves to protect and shield draenei souls from their eternal enemies: the Burning Legion, who hunger eternally for draenei spirits. This fact makes it a location of particular interest to Gul&apos;dan and his Shadow Council, who seek to gain favor with their demonic masters.&quot;,&quot;location&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZonesResponse {
            get {
                return ResourceManager.GetString("ZonesResponse", resourceCulture);
            }
        }
    }
}
