//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgentPonyWarcraftClient.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArgentPonyWarcraftClient.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:403, &quot;type&quot;:&quot;Forbidden&quot;, &quot;detail&quot;:&quot;Account Inactive&quot;}.
        /// </summary>
        internal static string AccountInactive403ForbiddenResponse {
            get {
                return ResourceManager.GetString("AccountInactive403ForbiddenResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement-category/?namespace=static-8.2.5_31884-us&quot;
        ///    }
        ///  },
        ///  &quot;categories&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement-category/81?namespace=static-8.2.5_31884-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Feats of Strength&quot;,
        ///      &quot;id&quot;: 81
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement-category/92?namespace=static-8.2.5_31884-us&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AchievementCategoriesIndexResponse {
            get {
                return ResourceManager.GetString("AchievementCategoriesIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement-category/81?namespace=static-8.2.5_31884-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 81,
        ///  &quot;name&quot;: &quot;Feats of Strength&quot;,
        ///  &quot;achievements&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement/456?namespace=static-8.2.5_31884-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Realm First! Obsidian Slayer&quot;,
        ///      &quot;id&quot;: 456
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AchievementCategoryResponse {
            get {
                return ResourceManager.GetString("AchievementCategoryResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/achievement/6?namespace=static-8.2.5_31884-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;icon&quot;,
        ///      &quot;value&quot;: &quot;https://render-us.worldofwarcraft.com/icons/56/achievement_level_10.jpg&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string AchievementMediaResponse {
            get {
                return ResourceManager.GetString("AchievementMediaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement/?namespace=static-8.2.5_31884-us&quot;
        ///    }
        ///  },
        ///  &quot;achievements&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement/6?namespace=static-8.2.5_31884-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Level 10&quot;,
        ///      &quot;id&quot;: 6
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement/7?namespace=static-8.2.5_31884-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Level 20&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AchievementsIndexResponse {
            get {
                return ResourceManager.GetString("AchievementsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/1146/auctions?namespace=dynamic-us&quot;
        ///    }
        ///  },
        ///  &quot;connected_realm&quot;: {
        ///    &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/1146?namespace=dynamic-us&quot;
        ///  },
        ///  &quot;auctions&quot;: [
        ///    {
        ///      &quot;id&quot;: 568957532,
        ///      &quot;item&quot;: {
        ///        &quot;id&quot;: 168185
        ///      },
        ///      &quot;quantity&quot;: 7,
        ///      &quot;unit_price&quot;: 345000,
        ///      &quot;time_left&quot;: &quot;SHORT&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 568957534,
        ///      &quot;item&quot;: {
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuctionsResponse {
            get {
                return ResourceManager.GetString("AuctionsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/profile/wow/character/norgannon/drinian/collections?namespace=profile-us&quot;
        ///    }
        ///  },
        ///  &quot;pets&quot;: {
        ///    &quot;href&quot;: &quot;https://us.api.blizzard.com/profile/wow/character/norgannon/drinian/collections/pets?namespace=profile-us&quot;
        ///  },
        ///  &quot;mounts&quot;: {
        ///    &quot;href&quot;: &quot;https://us.api.blizzard.com/profile/wow/character/norgannon/drinian/collections/mounts?namespace=profile-us&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string CharacterCollectionsIndexResponse {
            get {
                return ResourceManager.GetString("CharacterCollectionsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/profile/wow/character/norgannon/drinian/collections/mounts?namespace=profile-us&quot;
        ///    }
        ///  },
        ///  &quot;mounts&quot;: [
        ///    {
        ///      &quot;mount&quot;: {
        ///        &quot;key&quot;: {
        ///          &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/mount/6?namespace=static-8.3.0_32861-us&quot;
        ///        },
        ///        &quot;name&quot;: &quot;Brown Horse&quot;,
        ///        &quot;id&quot;: 6
        ///      }
        ///    },
        ///    {
        ///      &quot;mount&quot;: {
        ///        &quot;key&quot;: {
        ///          &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/mount/9? [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterMountsCollectionSummaryResponse {
            get {
                return ResourceManager.GetString("CharacterMountsCollectionSummaryResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/profile/wow/character/norgannon/drinian/collections/pets?namespace=profile-us&quot;
        ///    }
        ///  },
        ///  &quot;pets&quot;: [
        ///    {
        ///      &quot;species&quot;: {
        ///        &quot;key&quot;: {
        ///          &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pet/202?namespace=static-8.3.0_32861-us&quot;
        ///        },
        ///        &quot;name&quot;: &quot;Baby Blizzard Bear&quot;,
        ///        &quot;id&quot;: 202
        ///      },
        ///      &quot;level&quot;: 1,
        ///      &quot;quality&quot;: {
        ///        &quot;type&quot;: &quot;UNCOMMON&quot;,
        ///        &quot;name&quot;: &quot;Uncommon&quot;
        ///      },
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterPetsCollectionSummaryResponse {
            get {
                return ResourceManager.GetString("CharacterPetsCollectionSummaryResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/profile/wow/character/norgannon/drinian/status?namespace=profile-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 107811065,
        ///  &quot;is_valid&quot;: true
        ///}.
        /// </summary>
        internal static string CharacterProfileStatusResponse {
            get {
                return ResourceManager.GetString("CharacterProfileStatusResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/profile/wow/character/norgannon/drinian?namespace=profile-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 107811065,
        ///  &quot;name&quot;: &quot;Drinian&quot;,
        ///  &quot;gender&quot;: {
        ///    &quot;type&quot;: &quot;MALE&quot;,
        ///    &quot;name&quot;: &quot;Male&quot;
        ///  },
        ///  &quot;faction&quot;: {
        ///    &quot;type&quot;: &quot;ALLIANCE&quot;,
        ///    &quot;name&quot;: &quot;Alliance&quot;
        ///  },
        ///  &quot;race&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-race/1?namespace=static-8.3.0_32861-us&quot;
        ///    },
        ///    &quot;name&quot;: &quot;Human&quot;,
        ///    &quot;id&quot;: 1
        ///  },
        ///  &quot;char [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterProfileSummaryResponse {
            get {
                return ResourceManager.GetString("CharacterProfileSummaryResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement/6?namespace=static-8.2.5_31884-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 6,
        ///  &quot;category&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/achievement-category/92?namespace=static-8.2.5_31884-us&quot;
        ///    },
        ///    &quot;name&quot;: &quot;Character&quot;,
        ///    &quot;id&quot;: 92
        ///  },
        ///  &quot;name&quot;: &quot;Level 10&quot;,
        ///  &quot;description&quot;: &quot;Reach level 10.&quot;,
        ///  &quot;points&quot;: 10,
        ///  &quot;is_account_wide&quot;: false,
        ///  &quot;criteria&quot;: {
        ///    &quot;id&quot;: 2050,
        ///    &quot;description&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameDataAchievementResponse {
            get {
                return ResourceManager.GetString("GameDataAchievementResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:404,&quot;type&quot;:&quot;BLZWEBAPI00000404&quot;,&quot;detail&quot;:&quot;Not Found&quot;}.
        /// </summary>
        internal static string Item404ErrorResponse {
            get {
                return ResourceManager.GetString("Item404ErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;item_classes&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Consumable&quot;,
        ///      &quot;id&quot;: 0
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/1?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Container&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemClassesIndexResponse {
            get {
                return ResourceManager.GetString("ItemClassesIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;class_id&quot;: 0,
        ///  &quot;name&quot;: &quot;Consumable&quot;,
        ///  &quot;item_subclasses&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0/item-subclass/0?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Explosives and Devices&quot;,
        ///      &quot;id&quot;: 0
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-clas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemClassResponse {
            get {
                return ResourceManager.GetString("ItemClassResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/item/19019?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;icon&quot;,
        ///      &quot;value&quot;: &quot;https://render-us.worldofwarcraft.com/icons/56/inv_sword_39.jpg&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 19019
        ///}.
        /// </summary>
        internal static string ItemMediaResponse {
            get {
                return ResourceManager.GetString("ItemMediaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item/19019?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 19019,
        ///  &quot;name&quot;: &quot;Thunderfury, Blessed Blade of the Windseeker&quot;,
        ///  &quot;quality&quot;: {
        ///    &quot;type&quot;: &quot;LEGENDARY&quot;,
        ///    &quot;name&quot;: &quot;Legendary&quot;
        ///  },
        ///  &quot;level&quot;: 58,
        ///  &quot;required_level&quot;: 60,
        ///  &quot;media&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/item/19019?namespace=static-8.3.0_32861-us&quot;
        ///    },
        ///    &quot;id&quot;: 19019
        ///  },
        ///  &quot;item_class&quot;: {        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemResponse {
            get {
                return ResourceManager.GetString("ItemResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-set/1?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 1,
        ///  &quot;name&quot;: &quot;The Gladiator&quot;,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item/11729?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Savage Gladiator Helm&quot;,
        ///      &quot;id&quot;: 11729
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item/11726?namespace=static-8.3.0_32861 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemSetResponse {
            get {
                return ResourceManager.GetString("ItemSetResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-set/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;item_sets&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-set/1?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;The Gladiator&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-set/41?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Dal&apos;Rend&apos;s Arms&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemSetsIndexResponse {
            get {
                return ResourceManager.GetString("ItemSetsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0/item-subclass/0?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;class_id&quot;: 0,
        ///  &quot;subclass_id&quot;: 0,
        ///  &quot;display_name&quot;: &quot;Explosives and Devices&quot;,
        ///  &quot;hide_subclass_in_tooltips&quot;: true
        ///}.
        /// </summary>
        internal static string ItemSubclassResponse {
            get {
                return ResourceManager.GetString("ItemSubclassResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-encounter/89?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 89,
        ///  &quot;name&quot;: &quot;Glubtok&quot;,
        ///  &quot;description&quot;: &quot;In a fit of rage, Glubtok unleashed his potent magical abilities and reduced his ogre mound to ash. Upon hearing of his destructive talents, the Defias hired the massive ogre mage to supervise their laborers as head foreman of the Deadmines.&quot;,
        ///  &quot;creatures&quot;: [
        ///    {
        ///      &quot;id&quot;: 358,
        ///      &quot;name&quot;: &quot;Glu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalEncounterResponse {
            get {
                return ResourceManager.GetString("JournalEncounterResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-encounter/89?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 89,
        ///  &quot;name&quot;: &quot;Glubtok&quot;,
        ///  &quot;description&quot;: &quot;In a fit of rage, Glubtok unlea.
        /// </summary>
        internal static string JournalEncounterResponseTruncated {
            get {
                return ResourceManager.GetString("JournalEncounterResponseTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-encounter/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;encounters&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-encounter/89?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Glubtok&quot;,
        ///      &quot;id&quot;: 89
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-encounter/90?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalEncountersIndexResponse {
            get {
                return ResourceManager.GetString("JournalEncountersIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-expansion/68?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 68,
        ///  &quot;name&quot;: &quot;Classic&quot;,
        ///  &quot;dungeons&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-instance/227?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Blackfathom Deeps&quot;,
        ///      &quot;id&quot;: 227
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-instance/228?namesp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalExpansionResponse {
            get {
                return ResourceManager.GetString("JournalExpansionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-expansion/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;tiers&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-expansion/68?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Classic&quot;,
        ///      &quot;id&quot;: 68
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-expansion/70?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalExpansionsIndexResponse {
            get {
                return ResourceManager.GetString("JournalExpansionsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/journal-instance/63?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;tile&quot;,
        ///      &quot;value&quot;: &quot;https://render-us.worldofwarcraft.com/zones/deadmines-small.jpg&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string JournalInstanceMediaResponse {
            get {
                return ResourceManager.GetString("JournalInstanceMediaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-instance/63?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 63,
        ///  &quot;name&quot;: &quot;Deadmines&quot;,
        ///  &quot;map&quot;: {
        ///    &quot;name&quot;: &quot;Deadmines&quot;,
        ///    &quot;id&quot;: 36
        ///  },
        ///  &quot;area&quot;: {
        ///    &quot;name&quot;: &quot;The Deadmines&quot;,
        ///    &quot;id&quot;: 1581
        ///  },
        ///  &quot;description&quot;: &quot;It is said the Deadmines&apos; gold deposits once accounted for a third of Stormwind&apos;s treasure reserves. Amid the chaos of the First War, the mines were abandoned and later thought to be [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalInstanceResponse {
            get {
                return ResourceManager.GetString("JournalInstanceResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-instance/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;instances&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-instance/63?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Deadmines&quot;,
        ///      &quot;id&quot;: 63
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/journal-instance/64?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalInstancesIndexResponse {
            get {
                return ResourceManager.GetString("JournalInstancesIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/mount/6?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 6,
        ///  &quot;name&quot;: &quot;Brown Horse&quot;,
        ///  &quot;creature_displays&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/creature-display/2404?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;id&quot;: 2404
        ///    }
        ///  ],
        ///  &quot;description&quot;: &quot;A favorite among Stormwind&apos;s guards thanks to its patience and stamina.&quot;,
        ///  &quot;source&quot;: {
        ///    &quot;type&quot;: &quot;VENDOR&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MountResponse {
            get {
                return ResourceManager.GetString("MountResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/mount/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;mounts&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/mount/6?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Brown Horse&quot;,
        ///      &quot;id&quot;: 6
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/mount/7?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Gray Wolf&quot;,
        ///      &quot;id&quot;: 7
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MountsIndexResponse {
            get {
                return ResourceManager.GetString("MountsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pet/39?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 39,
        ///  &quot;name&quot;: &quot;Mechanical Squirrel&quot;,
        ///  &quot;battle_pet_type&quot;: {
        ///    &quot;id&quot;: 9,
        ///    &quot;type&quot;: &quot;MECHANICAL&quot;,
        ///    &quot;name&quot;: &quot;Mechanical&quot;
        ///  },
        ///  &quot;description&quot;: &quot;A mechanical squirrel&apos;s logic center tells it to collect and store both nuts and bolts for the winter.&quot;,
        ///  &quot;is_capturable&quot;: false,
        ///  &quot;is_tradable&quot;: true,
        ///  &quot;is_battlepet&quot;: true,
        ///  &quot;is_alliance_only&quot;: false,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PetResponse {
            get {
                return ResourceManager.GetString("PetResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pet/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;pets&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pet/39?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Mechanical Squirrel&quot;,
        ///      &quot;id&quot;: 39
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pet/40?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Bombay Cat&quot;,
        ///      &quot;id&quot;: 40        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PetsIndexResponse {
            get {
                return ResourceManager.GetString("PetsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-class/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;classes&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-class/1?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Warrior&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-class/2?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Paladin&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayableClassesIndexResponse {
            get {
                return ResourceManager.GetString("PlayableClassesIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/playable-class/7?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;icon&quot;,
        ///      &quot;value&quot;: &quot;https://render-us.worldofwarcraft.com/icons/56/classicon_shaman.jpg&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 7
        ///}.
        /// </summary>
        internal static string PlayableClassMediaResponse {
            get {
                return ResourceManager.GetString("PlayableClassMediaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-class/7?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 7,
        ///  &quot;name&quot;: &quot;Shaman&quot;,
        ///  &quot;gender_name&quot;: {
        ///    &quot;male&quot;: &quot;Shaman&quot;,
        ///    &quot;female&quot;: &quot;Shaman&quot;
        ///  },
        ///  &quot;power_type&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/power-type/0?namespace=static-8.3.0_32861-us&quot;
        ///    },
        ///    &quot;name&quot;: &quot;Mana&quot;,
        ///    &quot;id&quot;: 0
        ///  },
        ///  &quot;specializations&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.ap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayableClassResponse {
            get {
                return ResourceManager.GetString("PlayableClassResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-race/2?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 2,
        ///  &quot;name&quot;: &quot;Orc&quot;,
        ///  &quot;gender_name&quot;: {
        ///    &quot;male&quot;: &quot;Orc&quot;,
        ///    &quot;female&quot;: &quot;Orc&quot;
        ///  },
        ///  &quot;faction&quot;: {
        ///    &quot;type&quot;: &quot;HORDE&quot;,
        ///    &quot;name&quot;: &quot;Horde&quot;
        ///  },
        ///  &quot;is_selectable&quot;: true,
        ///  &quot;is_allied_race&quot;: false
        ///}.
        /// </summary>
        internal static string PlayableRaceResponse {
            get {
                return ResourceManager.GetString("PlayableRaceResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-race/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;races&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-race/1?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Human&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-race/2?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Orc&quot;,
        ///      &quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayableRacesIndexResponse {
            get {
                return ResourceManager.GetString("PlayableRacesIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-class/7/pvp-talent-slots?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;talent_slots&quot;: [
        ///    {
        ///      &quot;slot_number&quot;: 1,
        ///      &quot;unlock_player_level&quot;: 20
        ///    },
        ///    {
        ///      &quot;slot_number&quot;: 2,
        ///      &quot;unlock_player_level&quot;: 40
        ///    },
        ///    {
        ///      &quot;slot_number&quot;: 3,
        ///      &quot;unlock_player_level&quot;: 70
        ///    },
        ///    {
        ///      &quot;slot_number&quot;: 4,
        ///      &quot;unlock_player_level&quot;: 110
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string PvpTalentSlotsResponse {
            get {
                return ResourceManager.GetString("PvpTalentSlotsResponse", resourceCulture);
            }
        }
    }
}
